name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prd

permissions: {}

jobs:
  terraform-destroy:
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment == 'prd' && 'Production' || 'Development' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Terraform Init
        shell: bash
        run: |
          cd terraform
          terraform init -backend-config=${{ inputs.environment == 'prd' && 'backends/prd.backend.hcl' || 'backends/dev.backend.hcl' }} -var-file=${{ inputs.environment == 'prd' && 'tfvars/prd.tfvars' || 'tfvars/dev.tfvars' }}
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true

      - uses: frasermolyneux/actions/terraform-destroy@terraform-destroy/v1.2
        with:
          terraform-folder: "terraform"
          terraform-var-file: ${{ inputs.environment == 'prd' && 'tfvars/prd.tfvars' || 'tfvars/dev.tfvars' }}
          terraform-backend-file: ${{ inputs.environment == 'prd' && 'backends/prd.backend.hcl' || 'backends/dev.backend.hcl' }}
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          perform-checkout: "false"
